# Generated by Django 2.0.7 on 2018-08-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('quantity', models.IntegerField(default=None)),
                ('authors', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authors_app.Author')),
            ],
        ),
    ]
